import { z } from 'zod'
import { apiPost } from '../code-index/api-client.js'

export const SetDomainMembershipSchema = z.object({
  domain_id: z.string().min(1).describe('Existing Domain ID (Domain rows are created separately via the web app / API, NOT by this tool). Obtain from the domains list in the Tentra web UI. Example: "dom_payments".'),
  entity_type: z.enum(['file', 'symbol', 'service']).describe('What the entity_id refers to. "file" = CodeFile ID from index_code output, "symbol" = CodeSymbol ID from query_symbols, "service" = Tentra canvas service id (snake_case string like "payment_service").'),
  entity_id: z.string().min(1).describe('The ID of the entity being tagged. Must match entity_type: a CodeFile id, a CodeSymbol id, or a canvas service_id string.'),
  confidence: z.number().min(0).max(1).default(1.0)
    .describe('How sure you are about this domain assignment, 0–1. Default 1.0 (human-confirmed = certain). Use ~0.6–0.8 for AI-inferred bulk tagging so a human can review low-confidence rows later.'),
  source: z.enum(['ai', 'human']).default('human')
    .describe('Provenance of this assignment. "human" (default) = user explicitly confirmed. "ai" = generated by an agent; typically paired with confidence < 1.0 and meant to be reviewed / overridden by a human.')
})

export async function setDomainMembershipHandler(raw: unknown) {
  const args = SetDomainMembershipSchema.parse(raw)

  const result = await apiPost<{ id: string }>(
    `/code-graph/domains/${args.domain_id}/memberships`,
    {
      entity_type: args.entity_type,
      entity_id: args.entity_id,
      confidence: args.confidence,
      source: args.source
    }
  )

  return {
    content: [{
      type: 'text' as const,
      text: JSON.stringify({ ok: true, membership_id: result.id })
    }]
  }
}
